version: "3"

services:

  api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: billing-tools
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=billingtools/flask_app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - TZ=Canada/Eastern
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
    ports:
      - "5050:80"

  redis:
    image: redis:alpine